/* Botany hidden-route scope classification. NEET Core is the exam-facing set; Extension is useful enrichment; Advanced is research/degree-level detail and is not part of the main NEET path. */
window.skillUpBotanyScope={
  version:"20260923-final-audit-v1",
  core:[
  "plant families",
  "independent assortment",
  "x linked inheritance",
  "y linked inheritance",
  "mitochondrial inheritance",
  "chromosomal disorders",
  "mendelian disorders",
  "genetic variation",
  "genetic recombination",
  "tissue culture",
  "micropropagation",
  "gene silencing"
],
  extension:[
  "penetrance and expressivity",
  "quantitative inheritance",
  "genetic counseling",
  "genetic screening",
  "risk assessment",
  "carrier screening",
  "x-linked inheritance",
  "y-linked inheritance",
  "dna sequencing",
  "patent disputes traditional knowledge",
  "plant genetic engineering",
  "gene transfer methods",
  "plant transformation",
  "agrobacterium mediated transformation",
  "ti plasmid",
  "t dna",
  "x-chromosome inactivation",
  "dosage compensation",
  "parent of origin effects",
  "micro rna",
  "small interfering rna",
  "rna induced silencing complex",
  "dna cloning"
],
  advanced:[
  "gene environment interaction",
  "prenatal diagnosis",
  "amniocentesis",
  "chorionic villus sampling",
  "genetic testing",
  "gene therapy",
  "crispr and genome editing",
  "crispr genome editing",
  "crispr",
  "southern blotting",
  "northern blotting",
  "western blotting",
  "dna libraries",
  "cdna",
  "expression vectors",
  "patents intellectual property",
  "plant transformation vectors",
  "t-dna",
  "vir genes",
  "vira virg signaling",
  "vird tdna processing",
  "vire2 tdna protection",
  "type iv secretion system",
  "plant genome integration",
  "transgene integration",
  "risc",
  "dicer and argonaute",
  "sirna",
  "microrna",
  "mirna biogenesis",
  "mirna targeting",
  "mirna mediated gene silencing",
  "mirna gene silencing",
  "mirna target mimics",
  "mirna plant development",
  "mirna stress responses",
  "sirna vs mirna",
  "rddm",
  "dna methylation epigenetic silencing",
  "dna methylation",
  "histone modification chromatin remodeling",
  "histone chromatin remodeling",
  "epigenetic regulation gene expression",
  "epigenetic gene expression",
  "genomic imprinting",
  "x chromosome inactivation",
  "genomic imprinting vs x chromosome inactivation",
  "imprinting vs x inactivation",
  "epigenetic inheritance transgenerational effects",
  "epigenetic inheritance",
  "rna directed dna methylation",
  "sirna vs mirna comparison",
  "mirna stress",
  "mirna development",
  "mirna sponges",
  "mirna gene regulation",
  "mirna-biogenesis",
  "microRNA",
  "dicer argonaute",
  "rna interference advanced",
  "vir e2 tdna protection",
  "vird t-dna processing",
  "virA virG signaling"
]
};
